[phases.setup]
nixPkgs = ['...', 'nodejs', 'php82', 'php82Packages.composer']

[phases.install]
cmds = [
  'composer install --no-dev --optimize-autoloader --no-interaction',
  'npm ci --include=dev',
  'npm run build',
  'chmod +x railway-start.sh'
]

[start]
cmd = 'bash railway-start.sh'
